In [1]:
# 3 NumPy Arrays
import numpy as np

In [2]:
# 3.1 1d NumPy Arrays
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

In [3]:
print(arr * 4)

[ 80 108  36  48 124  68  16 200 156 140]


In [4]:
print(np.mean(arr))

24.4


In [5]:
print(np.median(arr))

23.5


In [6]:
print(np.std(arr))

13.828955130450023


In [7]:
print(np.argmin(arr))
print(np.argmax(arr))

6
7


In [8]:
print(arr[np.argmin(arr)])
print(arr[np.argmax(arr)])

4
50


In [9]:
print(np.min(arr))
print(np.max(arr))

4
50


In [10]:
greater_than_20 = arr[arr > 20]
print(greater_than_20)

[27 31 50 39 35]


In [11]:
# 3.2 2D NumPy Arrays
matrix = np.array([[5, 12, 17, 9],
          [8, 21, 14, 3],
          [6, 13, 19, 11]])

In [12]:
print(matrix.shape)
# 3 rows, 4 columns

(3, 4)


In [13]:
print(matrix[:, 2])

[17 14 19]


In [14]:
print(matrix[1, :])

[ 8 21 14  3]


In [15]:
print(matrix * 2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [16]:
print(np.mean(matrix, axis = 0))

[ 6.33333333 15.33333333 16.66666667  7.66666667]


In [17]:
print(np.mean(matrix))

11.5


In [18]:
print(np.max(matrix, axis = 1))
print(np.min(matrix, axis = 0))

[17 21 19]
[ 5 12 14  3]


In [19]:
print(matrix.flatten())
" It is now a 1D array, where the rows have been flattened into 1 row."

[ 5 12 17  9  8 21 14  3  6 13 19 11]


' It is now a 1D array, where the rows have been flattened into 1 row.'

In [20]:
print(np.argmin(matrix))
print(np.argmax(matrix))

7
5


In [21]:
print(np.unravel_index(np.argmin(matrix), matrix.shape))
print(np.unravel_index(np.argmax(matrix), matrix.shape))

(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))


In [22]:
print(matrix[matrix > 15])

[17 21 19]


In [23]:
print(np.sort(matrix, axis = 1))

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [24]:
# 4 Prime Star Systems
arr = np.array([[2, 3, 5],
               [14, 6, 8,],
               [11, 13, 17],
               [7, 10, 13]])

def prime_matrix(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True
rows_with_prime = np.array([row for row in arr if any(prime_matrix(x) for x in row)])
print(rows_with_prime)

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [25]:
# 5 Let's Play Checkers!
# 5.1 
def eight_by_eight_zeros():
    board = np.zeros((8, 8))
    return board

# 5.2 and 5.3
def checkerboard():
    board = np.zeros((8, 8))
    for i in range(8):
        for j in range(8):
            if (i + j) % 2 == 0:
                board[i, j] = 1
    return board
print(checkerboard())

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [26]:
# 5.4
def reverse_checkerboard():
    board = np.zeros((8, 8))
    for i in range(8):
        for j in range(8):
            if (i + j) % 2 == 0:
                board[i, j] = 1
    return 1 - board
print(reverse_checkerboard())

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [27]:
#6 The Expanding Universe
def expansion(words, n):
    expanded = [' '.join((word)).replace(' ', ' ' * (n + 1)) for word in words]
    return np.array(expanded)
example = np.array(['galaxy', 'clusters'])
print(expansion(example, 1))

['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [28]:
# 7 Second-Brightest Star
def second_brightest(stars):
    sorted_rows = np.sort(stars, axis = 1)
    return sorted_rows[:, -2]
# ex:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)
print(second_brightest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
